#include "util.h"
#include <map>
#include <list>

using namespace std;

class AutocompleteSystem {
public:
    AutocompleteSystem(vector<string>& sentences, vector<int>& times) {
        trie.clear();
        for(int i = 0; i < sentences.size(); i++) {
            trie[sentences[i]] = times[i];
        }
    }
    
    vector<string> input(char c) {
        if (c == '#') {
            trie[cur]+=1;
            cur = "";
            return vector<string>();
        } else {
            cur+=c;
            vector<string> rtn;
            vector<pair<string, int>> waitlist;
            for(auto itr = trie.lower_bound(cur);
                itr != trie.end() && itr->first.substr(0, cur.size()) == cur;
                itr++) {
                waitlist.push_back(*itr);
            }
            stable_sort(waitlist.begin(), waitlist.end(), [](const pair<string, int>& a, const pair<string, int>& b){return (a.second > b.second) || lexicographical_compare(a.first.begin(), a.first.end(), b.first.begin(), b.first.end());});
            for(int i = 0; i < waitlist.size() && i < 3; i++) {
                rtn.push_back(waitlist[i].first);
            }
            return rtn;
        }
    }
private:
    map<string, int> trie;
    string cur;
};

int main() {
    vector<string> sentences = {"cc cc ccccc","c c ccccc","cc cccc c c","cc","cc cc","cc c ccccc ccc","ccc c","cc cccc","ccccc cc cccc","ccccc cccc cc","cc ccccc cc cccc","ccc ccccc cccc","cccc cccc ccc","cc ccc","cc c","cccc ccc","ccc","cc cc cc","ccc c ccc cccc","c","ccc cc cc ccc","c cc","cccc","ccccc ccccc","ccc cccc ccccc","cccc ccc c","ccc c ccccc ccccc","ccccc ccc","cccc c","cccc cccc ccccc","cc ccc c ccc","ccccc","cc ccccc","ccc cccc c","c c","ccc ccccc ccccc","ccccc ccccc ccc cccc","ccccc cccc ccccc","ccccc ccccc c","cccc ccccc","ccccc cc","c cc c","ccc cc cc","cccc c cccc","c ccc cc cccc","c ccc","cc cc ccc","ccc ccc","ccccc cccc cc cccc","c ccccc","ccc c cc","cccc cccc cc ccccc","ccccc ccc cc ccc","c ccccc cc ccc","c cccc","c cc ccc ccc"};
    vector<int> times = {4,5,3,4,2,4,3,3,5,1,1,5,5,1,4,3,2,5,3,4,5,2,5,2,3,4,4,3,1,2,2,3,4,2,1,5,5,3,2,3,1,3,3,3,2,3,5,1,2,1,2,5,5,1,4,2};
    AutocompleteSystem* obj = new AutocompleteSystem(sentences, times);
    cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input(' ')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('c')) << endl;
cout << stringVectorToString(obj->input('#')) << endl;
    return 0;
}
